/**
 * EventmapApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleEvent } from './simpleEvent';
import { WikipediaSummary } from './wikipediaSummary';


export interface ExpandedEvent { 
    basics: SimpleEvent;
    wikipedia?: WikipediaSummary | null;
}

