/**
 * EventmapApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';


export interface SimpleEvent { 
    id: string;
    name?: string | null;
    venueName?: string | null;
    location?: Location | null;
}

